### PR TITLE
Filter comments in the list file as well as empty lines.

### LINKED ISSUE #106: Allow filtering comments in `repo-name-list-file`
For those using `action-sync` for GHES with large `repo-name-list-file`s, it would be nice to organize the file with comments.

### PR DESCRIPTION
**Pull request by bhundven**
It's handy to have comments in the list file so that you describe to other teams that may have different destination repos where to put actions to sync.

closes #106

### CODE REVIEW

**Review by susanzhang27 — APPROVED** [review]

**Comment by bhundven** [comment]
Rebased with`main` to bring this up to date.

**Comment by bhundven** [comment]
Rebased again. Workflow was failing on the license job?

**Comment by shawnHartsell** [comment]
> Rebased again. Workflow was failing on the license job?

+1 It was probably failing b/c we just merged in a batch of dependabot updates. Thanks for the contribution! I'll merge this in shortly 🚀

**Comment by bhundven** [comment]
Ok, updated again to pull in any new dependencies.

**Pull request merged**
